version: "3.9"
services:
  sever_web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    networks:
      - estudo
  server_php_fpm:
    build: .
    volumes:
      - ./:/var/www
    networks:
      - estudo
  db_postgres_sql:
    image: postgres:12
    container_name: pgsql_estudo
    restart: always
    tty: true
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=estudo_db
      - PGDATA=/var/lib/postgresql/data/db-files/
    networks:
      - estudo
volumes:
  postgres_data:
    driver: local

networks:
  estudo:
    name: network_estudo
    driver: bridge
