version: "3.9"
services:
  sever_web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    networks:
      - estudo
  server_php_fpm:
    build: .
    volumes:
      - ./:/var/www
    networks:
      - estudo

networks:
  estudo:
    name: network_estudo
    driver: bridge
